
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # NEXT_PUBLIC_BACKEND_URL is read at build time by Next.js
        NEXT_PUBLIC_BACKEND_URL: "http://backend:5000"
    environment:
      # and also available at runtime
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
